const fs = require('fs');
let c = fs.readFileSync('./src/components/ProtocolSnifferModal.tsx', 'utf8');
c = c.replace(/<MaterialCommunityIcons name="close" size={22} color="#FFF" \/>/g, '<MaterialCommunityIcons name="close" size={22} color="#000" />');
c = c.replace(/backgroundColor: '#111'/g, "backgroundColor: '#F5F5F7'");
c = c.replace(/backgroundColor: '#333', borderRadius: 20/g, "backgroundColor: '#E5E5EA', borderRadius: 20");
c = c.replace(/color: '#FFF' }/g, "color: '#000' }");
c = c.replace(/backgroundColor: '#000', borderRadius: 8, borderWidth: 1, borderColor: '#333', padding: 8/g, "backgroundColor: '#FFF', borderRadius: 8, borderWidth: 1, borderColor: '#E5E5EA', padding: 8");
c = c.replace(/color: '#bbb', fontSize: 12/g, "color: '#666', fontSize: 12");
c = c.replace(/backgroundColor: '#333', paddingLeft: 8/g, "backgroundColor: '#E5E5EA', paddingLeft: 8");
c = c.replace(/color: '#00f0ff'/g, "color: '#007AFF'");
c = c.replace(/color="#00f0ff"/g, 'color="#007AFF"');
c = c.replace(/backgroundColor: '#222', borderRadius: 8, padding: 12/g, "backgroundColor: '#F9F9F9', borderRadius: 8, padding: 12");
c = c.replace(/borderColor: '#333'/g, "borderColor: '#E5E5EA'");
c = c.replace(/<Text style={{ color: '#FFF', fontSize: 12 }}>Discoverable/g, "<Text style={{ color: '#000', fontSize: 12 }}>Discoverable");
c = c.replace(/backgroundColor: '#00AEEF'/g, "backgroundColor: '#007AFF'");
c = c.replace(/color: '#FFF', fontSize: 13/g, "color: '#000', fontSize: 13");
c = c.replace(/color: '#888', fontSize: 10/g, "color: '#666', fontSize: 10");
c = c.replace(/borderBottomColor: '#333'/g, "borderBottomColor: '#E5E5EA'");
c = c.replace(/snifferTarget === 'ALL' \? '#00f0ff' : '#222'/g, "snifferTarget === 'ALL' ? '#007AFF' : '#F0F0F0'");
c = c.replace(/snifferTarget === 'ALL' \? '#00f0ff' : '#444'/g, "snifferTarget === 'ALL' ? '#007AFF' : '#CCC'");
c = c.replace(/snifferTarget === 'ALL' \? '#000' : '#FFF'/g, "snifferTarget === 'ALL' ? '#FFF' : '#000'");
c = c.replace(/snifferTarget === d.id \? '#00f0ff' : '#222'/g, "snifferTarget === d.id ? '#007AFF' : '#F0F0F0'");
c = c.replace(/snifferTarget === d.id \? '#00f0ff' : '#444'/g, "snifferTarget === d.id ? '#007AFF' : '#CCC'");
c = c.replace(/snifferTarget === d.id \? '#000' : '#FFF'/g, "snifferTarget === d.id ? '#FFF' : '#000'");
c = c.replace(/backgroundColor: '#192518'/g, "backgroundColor: '#F0FDF4'");
c = c.replace(/borderColor: '#00ff8050'/g, "borderColor: '#A7F3D0'");
c = c.replace(/color: '#00ff80'/g, "color: '#16A34A'");
c = c.replace(/rgba\(0, 240, 255, 0.1\)/g, "#E0F2FE");
c = c.replace(/backgroundColor: '#000', padding: 8, borderRadius: 6, borderWidth: 1/g, "backgroundColor: '#FFF', padding: 8, borderRadius: 6, borderWidth: 1");
c = c.replace(/color: '#888', fontSize: 9/g, "color: '#666', fontSize: 9");
c = c.replace(/detectedPoints \? '#FFF' : '#444'/g, "detectedPoints ? '#000' : '#888'");
c = c.replace(/detectedSegments \? '#FFF' : '#444'/g, "detectedSegments ? '#000' : '#888'");
c = c.replace(/detectedColorOrder \? '#FFF' : '#444'/g, "detectedColorOrder ? '#000' : '#888'");
c = c.replace(/detectedStripType \? '#FFF' : '#444'/g, "detectedStripType ? '#000' : '#888'");
c = c.replace(/detectedFirmware \? '#FFF' : '#444'/g, "detectedFirmware ? '#000' : '#888'");
c = c.replace(/backgroundColor: '#FFF', padding: 12/g, "backgroundColor: '#FFF', padding: 12");
c = c.replace(/borderColor: '#00f0ff50'/g, "borderColor: '#BAE6FD'");
c = c.replace(/color: '#bbb', fontSize: 11/g, "color: '#666', fontSize: 11");
c = c.replace(/protocol === p \? '#00f0ff' : '#222'/g, "protocol === p ? '#007AFF' : '#F0F0F0'");
c = c.replace(/protocol === p \? '#000' : '#888'/g, "protocol === p ? '#FFF' : '#333'");
c = c.replace(/color: '#aaa', fontSize: 11/g, "color: '#666', fontSize: 11");
c = c.replace(/borderColor: '#FFF'/g, "borderColor: '#CCC'");
c = c.replace(/rgba\(255,165,0,0.1\)/g, "#FFF7ED");
c = c.replace(/color: '#FFA500'/g, "color: '#EA580C'");
c = c.replace(/primary: '#FFA500'/g, "primary: '#EA580C'");
c = c.replace(/primary: '#00FF44'/g, "primary: '#16A34A'");
c = c.replace(/rgba\(0,255,68,0.1\)/g, "#F0FDF4");
c = c.replace(/backgroundColor: '#222', padding: 12/g, "backgroundColor: '#F9F9F9', padding: 12");
c = c.replace(/borderColor: '#444'/g, "borderColor: '#E5E5EA'");
c = c.replace(/backgroundColor: '#111', color: '#FFF'/g, "backgroundColor: '#FFF', color: '#000'");
c = c.replace(/color: '#00AEEF'/g, "color: '#007AFF'");
c = c.replace(/borderColor: '#00AEEF'/g, "borderColor: '#007AFF'");
c = c.replace(/backgroundColor: '#222', color: '#FFF', borderColor: '#444'/g, "backgroundColor: '#F9F9F9', color: '#000', borderColor: '#E5E5EA'");
c = c.replace(/isSnifferPaused \? '#ff404020' : '#00ff8020'/g, "isSnifferPaused ? '#FEE2E2' : '#DCFCE7'");
c = c.replace(/isSnifferPaused \? '#ff4040' : '#00ff80'/g, "isSnifferPaused ? '#DC2626' : '#16A34A'");
c = c.replace(/color: '#555', fontFamily: 'monospace'/g, "color: '#888', fontFamily: 'monospace'");
c = c.replace(/item.dir === 'TX' \? '#FFD700' : '#00ff80'/g, "item.dir === 'TX' ? '#D97706' : '#16A34A'");
c = c.replace(/borderBottomColor: '#222'/g, "borderBottomColor: '#E5E5EA'");
fs.writeFileSync('./src/components/ProtocolSnifferModal.tsx', c, 'utf8');
console.log('done applying theme overrides');
