export const RBM_PATTERNS = [
  "Static",
  "Rainbow Jump",
  "7 Color Jump",
  "Red Green Jump",
  "Red Blue Jump",
  "Green Blue Jump",
  "Rainbow Gradual",
  "7 Color Gradual",
  "Red Green Gradual",
  "Red Blue Gradual",
  "Green Blue Gradual",
  "7 Color Strobe",
  "Red Strobe",
  "Green Strobe",
  "Blue Strobe",
  "Yellow Strobe",
  "Cyan Strobe",
  "Purple Strobe",
  "White Strobe",
  "7 Color Flow",
  "7 Color Chase",
  "7 Color Marquee",
  "7 Color Rain",
  "7 Color Breath",
  "7 Color Comet",
  "7 Color Wave",
  "7 Color Stack",
  "7 Color Trail",
  "7 Color Burst",
  "7 Color Scatter",
  "7 Color Beam",
  "7 Color Sparkle",
  "7 Color Sweep",
  "7 Color Ripple",
  "7 Color Starry",
  "7 Color Flash",
  "7 Color Pulse",
  "7 Color Spin",
  "7 Color Swing",
  "7 Color Twirl",
  "7 Color Glide",
  "Red Flow",
  "Green Flow",
  "Blue Flow",
  "Yellow Flow",
  "Cyan Flow",
  "Purple Flow",
  "White Flow",
  "Red Chase",
  "Green Chase",
  "Blue Chase",
  "Yellow Chase",
  "Cyan Chase",
  "Purple Chase",
  "White Chase",
  "Red Marquee",
  "Green Marquee",
  "Blue Marquee",
  "Yellow Marquee",
  "Cyan Marquee",
  "Purple Marquee",
  "White Marquee",
  "Red Rain",
  "Green Rain",
  "Blue Rain",
  "Yellow Rain",
  "Cyan Rain",
  "Purple Rain",
  "White Rain",
  "Red Breath",
  "Green Breath",
  "Blue Breath",
  "Yellow Breath",
  "Cyan Breath",
  "Purple Breath",
  "White Breath",
  "Red Comet",
  "Green Comet",
  "Blue Comet",
  "Yellow Comet",
  "Cyan Comet",
  "Purple Comet",
  "White Comet",
  "Red Wave",
  "Green Wave",
  "Blue Wave",
  "Yellow Wave",
  "Cyan Wave",
  "Purple Wave",
  "White Wave",
  "Firefly",
  "Meteor Wash",
  "Aurora",
  "Lightning",
  "Disco",
  "Neon City",
  "Forest Path",
  "Lava Lamp",
  "Ocean Drift",
  "Emergency",
  "Overlay circularly, 7 colors with white background from both ends to middle",
  "Overlay circularly, 7 colors with black background from middle to both sides and return back",
  "Overlay circularly, 7 colors with red background from middle to both sides and return back",
  "Overlay circularly, 7 colors with green background from middle to both sides and return back",
  "Overlay circularly, 7 colors with blue background from middle to both sides and return back",
  "Overlay circularly, 7 colors with yellow background from middle to both sides and return back",
  "Overlay circularly, 7 colors with purple background from middle to both sides and return back",
  "Overlay circularly, 7 colors with cyan background from middle to both sides and return back",
  "Overlay circularly, 7 colors with white background from middle to both sides and return back",
  "Fading out run circularly, 1point with black background from start to end",
  "Fading out run circularly, 1point with red background from start to end",
  "Fading out run circularly, 1point with green background from start to end",
  "Fading out run circularly, 1point with blue background from start to end",
  "Fading out run circularly, 1point with yellow background from start to end",
  "Fading out run circularly, 1point with purple background from start to end",
  "Fading out run circularly, 1point with cyan background from start to end",
  "Fading out run circularly, 1point with white background from start to end",
  "Fading out run circularly, 1point with black background from end to start",
  "Fading out run circularly, 1point with red background from end to start",
  "Fading out run circularly, 1point with green background from end to start",
  "Fading out run circularly, 1point with blue background from end to start",
  "Fading out run circularly, 1point with yellow background from end to start",
  "Fading out run circularly, 1point with purple background from end to start",
  "Fading out run circularly, 1point with cyan background from end to start",
  "Fading out run circularly, 1point with white background from end to start",
  "Fading out run circularly, 1point with black background from start to end and return back",
  "Fading out run circularly, 1point with red background from start to end and return back",
  "Fading out run circularly, 1point with green background from start to end and return back",
  "Fading out run circularly, 1point with blue background from start to end and return back",
  "Fading out run circularly, 1point with yellow background from start to end and return back",
  "Fading out run circularly, 1point with purple background from start to end and return back",
  "Fading out run circularly, 1point with cyan background from start to end and return back",
  "Fading out run circularly, 1point with white background from start to end and return back",
  "Flows in olivary circularly, 7 colors with black background from start to end",
  "Flows in olivary circularly, 7 colors with red background from start to end",
  "Flows in olivary circularly, 7 colors with green background from start to end",
  "Flows in olivary circularly, 7 colors with blue background from start to end",
  "Flows in olivary circularly, 7 colors with yellow background from start to end",
  "Flows in olivary circularly, 7 colors with purple background from start to end",
  "Flows in olivary circularly, 7 colors with cyan background from start to end",
  "Flows in olivary circularly, 7 colors with white background from start to end",
  "Flows in olivary circularly, 7 colors with black background from end to start",
  "Flows in olivary circularly, 7 colors with red background from end to start",
  "Flows in olivary circularly, 7 colors with green background from end to start",
  "Flows in olivary circularly, 7 colors with blue background from end to start",
  "Flows in olivary circularly, 7 colors with yellow background from end to start",
  "Flows in olivary circularly, 7 colors with purple background from end to start",
  "Flows in olivary circularly, 7 colors with cyan background from end to start",
  "Flows in olivary circularly, 7 colors with white background from end to start",
  "Flows in olivary circularly, 7 colors with black background from start to end and return back",
  "Flows in olivary circularly, 7 colors with red background from start to end and return back",
  "Flows in olivary circularly, 7 colors with green background from start to end and return back",
  "Flows in olivary circularly, 7 colors with blue background from start to end and return back",
  "Flows in olivary circularly, 7 colors with yellow background from start to end and return back",
  "Flows in olivary circularly, 7 colors with purple background from start to end and return back",
  "Flows in olivary circularly, 7 colors with cyan background from start to end and return back",
  "Flows in olivary circularly, 7 colors with white background from start to end and return back",
  "7 colors run circularly, each color in every 1 point with black background from start to end",
  "7 colors run circularly, each color in every 1 point with red background from start to end",
  "7 colors run circularly, each color in every 1 point with green background from start to end",
  "7 colors run circularly, each color in every 1 point with blue background from start to end",
  "7 colors run circularly, each color in every 1 point with yellow background from start to end",
  "7 colors run circularly, each color in every 1 point with purple background from start to end",
  "7 colors run circularly, each color in every 1 point with cyan background from start to end",
  "7 colors run circularly, each color in every 1 point with white background from start to end",
  "7 colors run circularly, each color in every 1 point with black background from end to start",
  "7 colors run circularly, each color in every 1 point with red background from end to start",
  "7 colors run circularly, each color in every 1 point with green background from end to start",
  "7 colors run circularly, each color in every 1 point with blue background from end to start",
  "7 colors run circularly, each color in every 1 point with yellow background from end to start",
  "7 colors run circularly, each color in every 1 point with purple background from end to start",
  "7 colors run circularly, each color in every 1 point with cyan background from end to start",
  "7 colors run circularly, each color in every 1 point with white background from end to start",
  "7 colors run circularly, each color in every 1 point with black background from start to end and return back",
  "7 colors run circularly, each color in every 1 point with red background from start to end and return back",
  "7 colors run circularly, each color in every 1 point with green background from start to end and return back",
  "7 colors run circularly, each color in every 1 point with blue background from start to end and return back",
  "7 colors run circularly, each color in every 1 point with yellow background from start to end and return back",
  "7 colors run circularly, each color in every 1 point with purple background from start to end and return back",
  "7 colors run circularly, each color in every 1 point with cyan background from start to end and return back",
  "7 colors run circularly, each color in every 1 point with white background from start to end and return back",
  "7 colors run circularly, each color in multi points with red background from start to end",
  "7 colors run circularly, each color in multi points with green background from start to end",
  "7 colors run circularly, each color in multi points with blue background from start to end",
  "7 colors run circularly, each color in multi points with yellow background from start to end",
  "7 colors run circularly, each color in multi points with purple background from start to end",
  "7 colors run circularly, each color in multi points with cyan background from start to end",
  "7 colors run circularly, each color in multi points with white background from start to end",
  "7 colors run circularly, each color in multi points with red background from end to start",
  "7 colors run circularly, each color in multi points with green background from end to start",
  "7 colors run circularly, each color in multi points with blue background from end to start",
  "7 colors run circularly, each color in multi points with yellow background from end to start",
  "7 colors run circularly, each color in multi points with purple background from end to start",
  "7 colors run circularly, each color in multi points with cyan background from end to start",
  "7 colors run circularly, each color in multi points with white background from end to start",
  "7 colors run circularly, each color in multi points with red background from start to end and return back",
  "7 colors run circularly, each color in multi points with green background from start to end and return back",
  "7 colors run circularly, each color in multi points with blue background from start to end and return back",
  "7 colors run circularly, each color in multi points with yellow background from start to end and return back",
  "7 colors run circularly, each color in multi points with purple background from start to end and return back",
  "7 colors run circularly, each color in multi points with cyan background from start to end and return back",
  "7 colors run circularly, each color in multi points with white background from start to end and return back",
  "Fading out run circularly, 7 colors each in red fading from start to end",
  "Fading out run circularly, 7 colors each in green fading from start to end",
  "Fading out run circularly, 7 colors each in blue fading from start to end",
  "Fading out run circularly, 7 colors each in yellow fading from start to end",
  "Fading out run circularly, 7 colors each in purple fading from start to end",
  "Fading out run circularly, 7 colors each in cyan fading from start to end",
  "Fading out run circularly, 7 colors each in white fading from start to end",
  "Fading out run circularly, 7 colors each in red fading from end to start",
  "Fading out run circularly, 7 colors each in green fading from end to start",
  "Fading out run circularly, 7 colors each in blue fading from end to start",
  "Fading out run circularly, 7 colors each in yellow fading from end to start",
  "Fading out run circularly, 7 colors each in purple fading from end to start",
  "Fading out run circularly, 7 colors each in cyan fading from end to start",
  "Fading out run circularly, 7 colors each in white fading from end to start",
  "Fading out run circularly, 7 colors each in red fading from start to end and return back",
  "Fading out run circularly, 7 colors each in green fading from start to end and return back",
  "Fading out run circularly, 7 colors each in blue fading from start to end and return back",
  "Fading out run circularly, 7 colors each in yellow fading from start to end and return back",
  "Fading out run circularly, 7 colors each in purple fading from start to end and return back",
  "Fading out run circularly, 7 colors each in cyan fading from start to end and return back",
  "Fading out run circularly, 7 colors each in white fading from start to end and return back",
  "7 colors each in red run circularly, multi points from start to end",
  "7 colors each in green run circularly, multi points from start to end",
  "7 colors each in blue run circularly, multi points from start to end",
  "7 colors each in yellow run circularly, multi points from start to end",
  "7 colors each in purple run circularly, multi points from start to end",
  "7 colors each in cyan run circularly, multi points from start to end",
  "7 colors each in white run circularly, multi points from start to end",
  "7 colors each in red run circularly, multi points from end to start",
  "7 colors each in green run circularly, multi points from end to start",
  "7 colors each in blue run circularly, multi points from end to start",
  "7 colors each in yellow run circularly, multi points from end to start",
  "7 colors each in purple run circularly, multi points from end to start",
  "7 colors each in cyan run circularly, multi points from end to start",
  "7 colors each in white run circularly, multi points from end to start",
  "7 colors each in red run circularly, multi points from start to end and return back",
  "7 colors each in green run circularly, multi points from start to end and return back",
  "And return back7 colors each in blue run circularly, multi points from start to end",
  "7 colors each in yellow run circularly, multi points from start to end and return back",
  "7 colors each in purple run circularly, multi points from start to end and return back",
  "7 colors each in cyan run circularly, multi points from start to end and return back",
  "7 colors each in white run circularly, multi points from start to end and return back",
  "Flows gradually and circularly, 6 colors with red background from start to end",
  "Flows gradually and circularly, 6 colors with green background from start to end",
  "Flows gradually and circularly, 6 colors with blue background from start to end",
  "Flows gradually and circularly, 6 colors with yellow background from start to end",
  "Flows gradually and circularly, 6 colors with purple background from start to end",
  "Flows gradually and circularly, 6 colors with cyan background from start to end",
  "Flows gradually and circularly, 6 colors with white background from start to end",
  "Flows gradually and circularly, 6 colors with red background from end to start",
  "Flows gradually and circularly, 6 colors with green background from end to start",
  "Flows gradually and circularly, 6 colors with blue background from end to start",
  "Flows gradually and circularly, 6 colors with yellow background from end to start",
  "Flows gradually and circularly, 6 colors with purple background from end to start",
  "Flows gradually and circularly, 6 colors with cyan background from end to start",
  "Flows gradually and circularly, 6 colors with white background from end to start",
  "Flows gradually and circularly, 6 colors with red background from start to end and return back",
  "Flows gradually and circularly, 6 colors with green background from start to end and return back",
  "Flows gradually and circularly, 6 colors with blue background from start to end and return back",
  "Flows gradually and circularly, 6 colors with yellow background from start to end and return back",
  "Flows gradually and circularly, 6 colors with purple background from start to end and return back",
  "Flows gradually and circularly, 6 colors with cyan background from start to end and return back",
  "Flows gradually and circularly, 6 colors with white background from start to end and return back",
  "7 colors run with black background from start to end",
  "7 colors run with red background from start to end",
  "7 colors run with green background from start to end",
  "7 colors run with blue background from start to end",
  "7 colors run with yellow background from start to end",
  "7 colors run with purple background from start to end",
  "7 colors run with cyan background from start to end",
  "7 colors run with white background from start to end",
  "7 colors run with black background from end to start",
  "7 colors run with red background from end to start",
  "7 colors run with green background from end to start",
  "7 colors run with blue background from end to start",
  "7 colors run with yellow background from end to start",
  "7 colors run with purple background from end to start",
  "7 colors run with cyan background from end to start",
  "7 colors run with white background from end to start",
  "7 colors run with black background from start to end and return back",
  "7 colors run with red background from start to end and return back",
  "7 colors run with green background from start to end and return back",
  "7 colors run with blue background from start to end and return back",
  "7 colors run with yellow background from start to end and return back",
  "7 colors run with purple background from start to end and return back",
  "7 colors run with cyan background from start to end and return back",
  "7 colors run with white background from start to end and return back",
  "7 colors run gradually + 7 colors run in olivary",
  "7 colors run gradually + 7 colors change quickly",
  "7 colors run gradually + 7 colors flash",
  "7 colors run in olivary + 7 colors change quickly",
  "7 colors run in olivary + 7 colors flash",
  "7 colors change quickly + 7 colors flash",
  "7 colors run gradually + 7 colors run in olivary + 7 colors change quickly",
  "7 colors run gradually + 7 colors run in olivary + 7 colors flash",
  "7 colors run gradually + 7 colors change quickly + 7 colors flash",
  "7 colors run in olivary + 7 colors change quickly + 7 colors flash",
  "7 colors run gradually + 7 colors run in olivary + 7 colors change quickly + 7 color flash"
];

export const getRbmPatternName = (index: number): string => {
  if (index === 103) {
    return 'Emergency Protocol';
  }
  if (index >= 1 && index <= RBM_PATTERNS.length) {
    return RBM_PATTERNS[index - 1];
  }
  return `Effect ${index}`;
};
