export const RBM_PATTERNS = [
  "Static",
  "Rainbow Jump",
  "7 Color Jump",
  "Red Green Jump",
  "Red Blue Jump",
  "Green Blue Jump",
  "Rainbow Gradual",
  "7 Color Gradual",
  "Red Green Gradual",
  "Red Blue Gradual",
  "Green Blue Gradual",
  "7 Color Strobe",
  "Red Strobe",
  "Green Strobe",
  "Blue Strobe",
  "Yellow Strobe",
  "Cyan Strobe",
  "Purple Strobe",
  "White Strobe",
  "7 Color Flow",
  "7 Color Chase",
  "7 Color Marquee",
  "7 Color Rain",
  "7 Color Breath",
  "7 Color Comet",
  "7 Color Wave",
  "7 Color Stack",
  "7 Color Trail",
  "7 Color Burst",
  "7 Color Scatter",
  "7 Color Beam",
  "7 Color Sparkle",
  "7 Color Ripple",
  "7 Color Starry",
  "7 Color Flash",
  "7 Color Pulse",
  "7 Color Spin",
  "7 Color Swing",
  "7 Color Twirl",
  "7 Color Glide",
  "Red Flow",
  "Green Flow",
  "Blue Flow",
  "Yellow Flow",
  "Cyan Flow",
  "Purple Flow",
  "White Flow",
  "Red Chase",
  "Green Chase",
  "Blue Chase",
  "Yellow Chase",
  "Cyan Chase",
  "Purple Chase",
  "White Chase",
  "Red Marquee",
  "Green Marquee",
  "Blue Marquee",
  "Yellow Marquee",
  "Cyan Marquee",
  "Purple Marquee",
  "White Marquee",
  "Red Rain",
  "Green Rain",
  "Blue Rain",
  "Yellow Rain",
  "Cyan Rain",
  "Purple Rain",
  "White Rain",
  "Red Breath",
  "Green Breath",
  "Blue Breath",
  "Yellow Breath",
  "Cyan Breath",
  "Purple Breath",
  "White Breath",
  "Red Comet",
  "Green Comet",
  "Blue Comet",
  "Yellow Comet",
  "Cyan Comet",
  "Purple Comet",
  "White Comet",
  "Red Wave",
  "Green Wave",
  "Blue Wave",
  "Yellow Wave",
  "Cyan Wave",
  "Purple Wave",
  "White Wave",
  "Firefly",
  "Meteor Wash",
  "Aurora",
  "Lightning",
  "Disco",
  "Neon City",
  "Forest Path",
  "Lava Lamp",
  "Ocean Drift"
];

// Fallback generator for the rest of the 100
export const getRbmPatternName = (index: number): string => {
  if (index >= 1 && index <= RBM_PATTERNS.length) {
    return RBM_PATTERNS[index - 1];
  }
  return `Pattern ${index}`;
};
