export const RBM_PATTERNS = [
  "Circulate all modes",
  "7 colors change gradually",
  "7 colors run in olivary",
  "7 colors change quickly",
  "7 colors strobe-flash",
  "7 colors running, 1 point from start to end and return back",
  "7 colors running, multi points from start to end and return back",
  "7 colors overlay, multi points from start to end and return back",
  "7 colors overlay, multi points from the middle to the both ends and return back",
  "7 colors flow gradually, from start to end and return back",
  "Fading out run, 7 colors from start to end and return back",
  "Runs in olivary, 7 colors from start to end and return back",
  "Fading out run, 7 colors start with white color from start to end and return back",
  "Run circularly, 7 colors with black background, 1point from start to end",
  "Run circularly, 7 colors with red background, 1point from start to end",
  "Run circularly, 7 colors with green background, 1point from start to end",
  "Run circularly, 7 colors with blue background, 1point from start to end",
  "Run circularly, 7 colors with yellow background, 1point from start to end",
  "Run circularly, 7 colors with purple background, 1point from start to end",
  "Run circularly, 7 colors with cyan background, 1point from start to end",
  "Run circularly, 7 colors with white background, 1point from start to end",
  "Run circularly, 7 colors with black background, 1point from end to start",
  "Run circularly, 7 colors with red background, 1point from end to start",
  "Run circularly, 7 colors with green background, 1point from end to start",
  "Run circularly, 7 colors with blue background, 1point from end to start",
  "Run circularly, 7 colors with yellow background, 1point from end to start",
  "Run circularly, 7 colors with purple background, 1point from end to start",
  "Run circularly, 7 colors with cyan background, 1point from end to start",
  "Run circularly, 7 colors with white background, 1point from end to start",
  "Run circularly, 7 colors with black background, 1point from start to end and return back",
  "Run circularly, 7 colors with red background, 1point from start to end and return back",
  "Run circularly, 7 colors with green background, 1point from start to end and return back",
  "Run circularly, 7 colors with blue background, 1point from start to end and return back",
  "Run circularly, 7 colors with yellow background, 1point from start to end and return back",
  "Run circularly, 7 colors with purple background, 1point from start to end and return back",
  "Run circularly, 7 colors with cyan background, 1point from start to end and return back",
  "Run circularly, 7 colors with white background, 1point from start to end and return back",
  "Run circularly, 7 colors with black background, 1point from middle to both ends",
  "Run circularly, 7 colors with red background, 1point from middle to both ends",
  "Run circularly, 7 colors with green background, 1point from middle to both ends",
  "Run circularly, 7 colors with blue background, 1point from middle to both ends",
  "Run circularly, 7 colors with yellow background, 1point from middle to both ends",
  "Run circularly, 7 colors with purple background, 1point from middle to both ends",
  "Run circularly, 7 colors with cyan background, 1point from middle to both ends",
  "Run circularly, 7 colors with white background, 1point from middle to both ends",
  "Run circularly, 7 colors with black background, 1point from both ends to middle",
  "Run circularly, 7 colors with red background, 1point from both ends to middle",
  "Run circularly, 7 colors with green background, 1point from both ends to middle",
  "Run circularly, 7 colors with blue background, 1point from both ends to middle",
  "Run circularly, 7 colors with yellow background, 1point from both ends to middle",
  "Run circularly, 7 colors with purple background, 1point from both ends to middle",
  "Run circularly, 7 colors with cyan background, 1point from both ends to middle",
  "Run circularly, 7 colors with white background, 1point from both ends to middle",
  "Run circularly, 7 colors with black background, 1point from middle to both ends and return back",
  "Run circularly, 7 colors with red background, 1point from middle to both ends and return back",
  "Run circularly, 7 colors with green background, 1point from middle to both ends and return back",
  "Run circularly, 7 colors with blue background, 1point from middle to both ends and return back",
  "Run circularly, 7 colors with yellow background, 1point from middle to both ends and return back",
  "Run circularly, 7 colors with purple background, 1point from middle to both ends and return back",
  "Run circularly, 7 colors with cyan background, 1point from middle to both ends and return back",
  "Run circularly, 7 colors with white background, 1point from middle to both ends and return back",
  "Overlay circularly, 7 colors with black background from start to end",
  "Overlay circularly, 7 colors with red background from start to end",
  "Overlay circularly, 7 colors with green background from start to end",
  "Overlay circularly, 7 colors with blue background from start to end",
  "Overlay circularly, 7 colors with yellow background from start to end",
  "Overlay circularly, 7 colors with purple background from start to end",
  "Overlay circularly, 7 colors with cyan background from start to end",
  "Overlay circularly, 7 colors with white background from start to end",
  "Overlay circularly, 7 colors with black background from end to start",
  "Overlay circularly, 7 colors with red background from end to start",
  "Overlay circularly, 7 colors with green background from end to start",
  "Overlay circularly, 7 colors with blue background from end to start",
  "Overlay circularly, 7 colors with yellow background from end to start",
  "Overlay circularly, 7 colors with purple background from end to start",
  "Overlay circularly, 7 colors with cyan background from end to start",
  "Overlay circularly, 7 colors with white background from end to start",
  "Overlay circularly, 7 colors with black background from start to end and return back",
  "Overlay circularly, 7 colors with red background from start to end and return back",
  "Overlay circularly, 7 colors with green background from start to end and return back",
  "Overlay circularly, 7 colors with blue background from start to end and return back",
  "Overlay circularly, 7 colors with yellow background from start to end and return back",
  "Overlay circularly, 7 colors with purple background from start to end and return back",
  "Overlay circularly, 7 colors with cyan background from start to end and return back",
  "Overlay circularly, 7 colors with white background from start to end and return back",
  "Overlay circularly, 7 colors with black background from middle to both ends",
  "Overlay circularly, 7 colors with red background from middle to both ends",
  "Overlay circularly, 7 colors with green background from middle to both ends",
  "Overlay circularly, 7 colors with blue background from middle to both ends",
  "Overlay circularly, 7 colors with yellow background from middle to both ends",
  "Overlay circularly, 7 colors with purple background from middle to both ends",
  "Overlay circularly, 7 colors with cyan background from middle to both ends",
  "Overlay circularly, 7 colors with white background from middle to both ends",
  "Overlay circularly, 7 colors with black background from both ends to middle",
  "Overlay circularly, 7 colors with red background from both ends to middle",
  "Overlay circularly, 7 colors with green background from both ends to middle",
  "Overlay circularly, 7 colors with blue background from both ends to middle",
  "Overlay circularly, 7 colors with yellow background from both ends to middle",
  "Overlay circularly, 7 colors with purple background from both ends to middle",
  "Overlay circularly, 7 colors with cyan background from both ends to middle",
  "Overlay circularly, 7 colors with white background from both ends to middle",
  "Overlay circularly, 7 colors with black background from middle to both sides and return back",
  "Overlay circularly, 7 colors with red background from middle to both sides and return back",
  "Overlay circularly, 7 colors with green background from middle to both sides and return back",
  "Overlay circularly, 7 colors with blue background from middle to both sides and return back",
  "Overlay circularly, 7 colors with yellow background from middle to both sides and return back",
  "Overlay circularly, 7 colors with purple background from middle to both sides and return back",
  "Overlay circularly, 7 colors with cyan background from middle to both sides and return back",
  "Overlay circularly, 7 colors with white background from middle to both sides and return back",
  "Fading out run circularly, 1point with black background from start to end",
  "Fading out run circularly, 1point with red background from start to end",
  "Fading out run circularly, 1point with green background from start to end",
  "Fading out run circularly, 1point with blue background from start to end",
  "Fading out run circularly, 1point with yellow background from start to end",
  "Fading out run circularly, 1point with purple background from start to end",
  "Fading out run circularly, 1point with cyan background from start to end",
  "Fading out run circularly, 1point with white background from start to end",
  "Fading out run circularly, 1point with black background from end to start",
  "Fading out run circularly, 1point with red background from end to start",
  "Fading out run circularly, 1point with green background from end to start",
  "Fading out run circularly, 1point with blue background from end to start",
  "Fading out run circularly, 1point with yellow background from end to start",
  "Fading out run circularly, 1point with purple background from end to start",
  "Fading out run circularly, 1point with cyan background from end to start",
  "Fading out run circularly, 1point with white background from end to start",
  "Fading out run circularly, 1point with black background from start to end and return back",
  "Fading out run circularly, 1point with red background from start to end and return back",
  "Fading out run circularly, 1point with green background from start to end and return back",
  "Fading out run circularly, 1point with blue background from start to end and return back",
  "Fading out run circularly, 1point with yellow background from start to end and return back",
  "Fading out run circularly, 1point with purple background from start to end and return back",
  "Fading out run circularly, 1point with cyan background from start to end and return back",
  "Fading out run circularly, 1point with white background from start to end and return back",
  "Flows in olivary circularly, 7 colors with black background from start to end",
  "Flows in olivary circularly, 7 colors with red background from start to end",
  "Flows in olivary circularly, 7 colors with green background from start to end",
  "Flows in olivary circularly, 7 colors with blue background from start to end",
  "Flows in olivary circularly, 7 colors with yellow background from start to end",
  "Flows in olivary circularly, 7 colors with purple background from start to end",
  "Flows in olivary circularly, 7 colors with cyan background from start to end",
  "Flows in olivary circularly, 7 colors with white background from start to end",
  "Flows in olivary circularly, 7 colors with black background from end to start",
  "Flows in olivary circularly, 7 colors with red background from end to start",
  "Flows in olivary circularly, 7 colors with green background from end to start",
  "Flows in olivary circularly, 7 colors with blue background from end to start",
  "Flows in olivary circularly, 7 colors with yellow background from end to start",
  "Flows in olivary circularly, 7 colors with purple background from end to start",
  "Flows in olivary circularly, 7 colors with cyan background from end to start",
  "Flows in olivary circularly, 7 colors with white background from end to start",
  "Flows in olivary circularly, 7 colors with black background from start to end and return back",
  "Flows in olivary circularly, 7 colors with red background from start to end and return back",
  "Flows in olivary circularly, 7 colors with green background from start to end and return back",
  "Flows in olivary circularly, 7 colors with blue background from start to end and return back",
  "Flows in olivary circularly, 7 colors with yellow background from start to end and return back",
  "Flows in olivary circularly, 7 colors with purple background from start to end and return back",
  "Flows in olivary circularly, 7 colors with cyan background from start to end and return back",
  "Flows in olivary circularly, 7 colors with white background from start to end and return back",
  "7 colors run circularly, each color in every 1 point with black background from start to end",
  "7 colors run circularly, each color in every 1 point with red background from start to end",
  "7 colors run circularly, each color in every 1 point with green background from start to end",
  "7 colors run circularly, each color in every 1 point with blue background from start to end",
  "7 colors run circularly, each color in every 1 point with yellow background from start to end",
  "7 colors run circularly, each color in every 1 point with purple background from start to end",
  "7 colors run circularly, each color in every 1 point with cyan background from start to end",
  "7 colors run circularly, each color in every 1 point with white background from start to end",
  "7 colors run circularly, each color in every 1 point with black background from end to start",
  "7 colors run circularly, each color in every 1 point with red background from end to start",
  "7 colors run circularly, each color in every 1 point with green background from end to start",
  "7 colors run circularly, each color in every 1 point with blue background from end to start",
  "7 colors run circularly, each color in every 1 point with yellow background from end to start",
  "7 colors run circularly, each color in every 1 point with purple background from end to start",
  "7 colors run circularly, each color in every 1 point with cyan background from end to start",
  "7 colors run circularly, each color in every 1 point with white background from end to start",
  "7 colors run circularly, each color in every 1 point with black background from start to end and return back",
  "7 colors run circularly, each color in every 1 point with red background from start to end and return back",
  "7 colors run circularly, each color in every 1 point with green background from start to end and return back",
  "7 colors run circularly, each color in every 1 point with blue background from start to end and return back",
  "7 colors run circularly, each color in every 1 point with yellow background from start to end and return back",
  "7 colors run circularly, each color in every 1 point with purple background from start to end and return back",
  "7 colors run circularly, each color in every 1 point with cyan background from start to end and return back",
  "7 colors run circularly, each color in every 1 point with white background from start to end and return back",
  "7 colors run circularly, each color in multi points with red background from start to end",
  "7 colors run circularly, each color in multi points with green background from start to end",
  "7 colors run circularly, each color in multi points with blue background from start to end",
  "7 colors run circularly, each color in multi points with yellow background from start to end",
  "7 colors run circularly, each color in multi points with purple background from start to end",
  "7 colors run circularly, each color in multi points with cyan background from start to end",
  "7 colors run circularly, each color in multi points with white background from start to end",
  "7 colors run circularly, each color in multi points with red background from end to start",
  "7 colors run circularly, each color in multi points with green background from end to start",
  "7 colors run circularly, each color in multi points with blue background from end to start",
  "7 colors run circularly, each color in multi points with yellow background from end to start",
  "7 colors run circularly, each color in multi points with purple background from end to start",
  "7 colors run circularly, each color in multi points with cyan background from end to start",
  "7 colors run circularly, each color in multi points with white background from end to start",
  "7 colors run circularly, each color in multi points with red background from start to end and return back",
  "7 colors run circularly, each color in multi points with green background from start to end and return back",
  "7 colors run circularly, each color in multi points with blue background from start to end and return back",
  "7 colors run circularly, each color in multi points with yellow background from start to end and return back",
  "7 colors run circularly, each color in multi points with purple background from start to end and return back",
  "7 colors run circularly, each color in multi points with cyan background from start to end and return back",
  "7 colors run circularly, each color in multi points with white background from start to end and return back",
  "Fading out run circularly, 7 colors each in red fading from start to end",
  "Fading out run circularly, 7 colors each in green fading from start to end",
  "Fading out run circularly, 7 colors each in blue fading from start to end",
  "Fading out run circularly, 7 colors each in yellow fading from start to end",
  "Fading out run circularly, 7 colors each in purple fading from start to end",
  "Fading out run circularly, 7 colors each in cyan fading from start to end",
  "Fading out run circularly, 7 colors each in white fading from start to end",
  "Fading out run circularly, 7 colors each in red fading from end to start",
  "Fading out run circularly, 7 colors each in green fading from end to start",
  "Fading out run circularly, 7 colors each in blue fading from end to start",
  "Fading out run circularly, 7 colors each in yellow fading from end to start",
  "Fading out run circularly, 7 colors each in purple fading from end to start",
  "Fading out run circularly, 7 colors each in cyan fading from end to start",
  "Fading out run circularly, 7 colors each in white fading from end to start",
  "Fading out run circularly, 7 colors each in red fading from start to end and return back",
  "Fading out run circularly, 7 colors each in green fading from start to end and return back",
  "Fading out run circularly, 7 colors each in blue fading from start to end and return back",
  "Fading out run circularly, 7 colors each in yellow fading from start to end and return back",
  "Fading out run circularly, 7 colors each in purple fading from start to end and return back",
  "Fading out run circularly, 7 colors each in cyan fading from start to end and return back",
  "Fading out run circularly, 7 colors each in white fading from start to end and return back",
  "7 colors each in red run circularly, multi points from start to end",
  "7 colors each in green run circularly, multi points from start to end",
  "7 colors each in blue run circularly, multi points from start to end",
  "7 colors each in yellow run circularly, multi points from start to end",
  "7 colors each in purple run circularly, multi points from start to end",
  "7 colors each in cyan run circularly, multi points from start to end",
  "7 colors each in white run circularly, multi points from start to end",
  "7 colors each in red run circularly, multi points from end to start",
  "7 colors each in green run circularly, multi points from end to start",
  "7 colors each in blue run circularly, multi points from end to start",
  "7 colors each in yellow run circularly, multi points from end to start",
  "7 colors each in purple run circularly, multi points from end to start",
  "7 colors each in cyan run circularly, multi points from end to start",
  "7 colors each in white run circularly, multi points from end to start",
  "7 colors each in red run circularly, multi points from start to end and return back",
  "7 colors each in green run circularly, multi points from start to end and return back",
  "And return back7 colors each in blue run circularly, multi points from start to end",
  "7 colors each in yellow run circularly, multi points from start to end and return back",
  "7 colors each in purple run circularly, multi points from start to end and return back",
  "7 colors each in cyan run circularly, multi points from start to end and return back",
  "7 colors each in white run circularly, multi points from start to end and return back",
  "Flows gradually and circularly, 6 colors with red background from start to end",
  "Flows gradually and circularly, 6 colors with green background from start to end",
  "Flows gradually and circularly, 6 colors with blue background from start to end",
  "Flows gradually and circularly, 6 colors with yellow background from start to end",
  "Flows gradually and circularly, 6 colors with purple background from start to end",
  "Flows gradually and circularly, 6 colors with cyan background from start to end",
  "Flows gradually and circularly, 6 colors with white background from start to end",
  "Flows gradually and circularly, 6 colors with red background from end to start",
  "Flows gradually and circularly, 6 colors with green background from end to start",
  "Flows gradually and circularly, 6 colors with blue background from end to start",
  "Flows gradually and circularly, 6 colors with yellow background from end to start",
  "Flows gradually and circularly, 6 colors with purple background from end to start",
  "Flows gradually and circularly, 6 colors with cyan background from end to start",
  "Flows gradually and circularly, 6 colors with white background from end to start",
  "Flows gradually and circularly, 6 colors with red background from start to end and return back",
  "Flows gradually and circularly, 6 colors with green background from start to end and return back",
  "Flows gradually and circularly, 6 colors with blue background from start to end and return back",
  "Flows gradually and circularly, 6 colors with yellow background from start to end and return back",
  "Flows gradually and circularly, 6 colors with purple background from start to end and return back",
  "Flows gradually and circularly, 6 colors with cyan background from start to end and return back",
  "Flows gradually and circularly, 6 colors with white background from start to end and return back",
  "7 colors run with black background from start to end",
  "7 colors run with red background from start to end",
  "7 colors run with green background from start to end",
  "7 colors run with blue background from start to end",
  "7 colors run with yellow background from start to end",
  "7 colors run with purple background from start to end",
  "7 colors run with cyan background from start to end",
  "7 colors run with white background from start to end",
  "7 colors run with black background from end to start",
  "7 colors run with red background from end to start",
  "7 colors run with green background from end to start",
  "7 colors run with blue background from end to start",
  "7 colors run with yellow background from end to start",
  "7 colors run with purple background from end to start",
  "7 colors run with cyan background from end to start",
  "7 colors run with white background from end to start",
  "7 colors run with black background from start to end and return back",
  "7 colors run with red background from start to end and return back",
  "7 colors run with green background from start to end and return back",
  "7 colors run with blue background from start to end and return back",
  "7 colors run with yellow background from start to end and return back",
  "7 colors run with purple background from start to end and return back",
  "7 colors run with cyan background from start to end and return back",
  "7 colors run with white background from start to end and return back",
  "7 colors run gradually + 7 colors run in olivary",
  "7 colors run gradually + 7 colors change quickly",
  "7 colors run gradually + 7 colors flash",
  "7 colors run in olivary + 7 colors change quickly",
  "7 colors run in olivary + 7 colors flash",
  "7 colors change quickly + 7 colors flash",
  "7 colors run gradually + 7 colors run in olivary + 7 colors change quickly",
  "7 colors run gradually + 7 colors run in olivary + 7 colors flash",
  "7 colors run gradually + 7 colors change quickly + 7 colors flash",
  "7 colors run in olivary + 7 colors change quickly + 7 colors flash",
  "7 colors run gradually + 7 colors run in olivary + 7 colors change quickly + 7 color flash",
];

export const getRbmPatternName = (index: number): string => {
  if (index >= 1 && index <= RBM_PATTERNS.length) {
    return `${index}: ${RBM_PATTERNS[index - 1]}`;
  }
  return `Effect ${index}`;
};
