ALTER TABLE skate_spots
ADD COLUMN has_food BOOLEAN DEFAULT NULL,
ADD COLUMN has_ac BOOLEAN DEFAULT NULL,
ADD COLUMN has_lockers BOOLEAN DEFAULT NULL,
ADD COLUMN capacity INTEGER DEFAULT NULL,
ADD COLUMN hosts_derby BOOLEAN DEFAULT NULL;
