ALTER TABLE skate_spots
ADD COLUMN has_lights BOOLEAN DEFAULT NULL,
ADD COLUMN has_fee BOOLEAN DEFAULT NULL,
ADD COLUMN operator_name TEXT DEFAULT NULL,
ADD COLUMN has_rental BOOLEAN DEFAULT NULL,
ADD COLUMN is_wheelchair_accessible BOOLEAN DEFAULT NULL,
ADD COLUMN has_wifi BOOLEAN DEFAULT NULL,
ADD COLUMN has_toilets BOOLEAN DEFAULT NULL,
ADD COLUMN operator_description TEXT DEFAULT NULL;
